# Generated by Django 4.2.2 on 2023-06-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_users_alter_customer_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
