# Generated by Django 4.2.2 on 2023-06-28 05:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_app', '0001_initial'),
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'delivery_status',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=300)),
                ('payment_status', models.CharField(max_length=300)),
                ('transaction', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_app.customer')),
                ('delivery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders_app.deliverystatus')),
                ('payment', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders_app.payment')),
                ('products', models.ManyToManyField(related_name='product_order', to='products_app.product')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
