# Generated by Django 4.2.2 on 2023-06-28 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products_app.image')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products_app.type')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('uploaded_by', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=40)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.image')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
