# Generated by Django 4.2.1 on 2023-06-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image_id', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products_app.image')),
                ('type_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products_app.type')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
