# Generated by Django 4.2.1 on 2023-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_id',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
