# Generated by Django 4.2.1 on 2023-06-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_alter_product_discount_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='products_app.image'),
        ),
    ]
