# Generated by Django 4.2.1 on 2023-06-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products_app.image'),
        ),
    ]
