# Generated by Django 4.2.1 on 2023-06-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_blog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
